export type CmoPillar = 'capacidad' | 'motivacion' | 'oportunidad';

export type InterventionCatalogItem = {
  code: string;
  label: string;
  domain: string;
  cmo_pillar: CmoPillar;
  min_level: 1 | 2 | 3;
};

export const INTERVENTION_CATALOG: InterventionCatalogItem[] = [
  // NIVEL 3 · BASAL
  {
    code: 'ptfu_basic_review',
    label: 'Seguimiento farmacoterapéutico básico',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'adherence_basic_monitoring',
    label: 'Monitorización básica de adherencia',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'motivacion',
    min_level: 3,
  },
  {
    code: 'medication_reconciliation_basic',
    label: 'Conciliación y revisión básica de medicación concomitante',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'cv_education_basic',
    label: 'Educación básica sobre enfermedad cardiovascular y tratamiento',
    domain: 'Health Education and Promotion of Healthy Lifestyles',
    cmo_pillar: 'capacidad',
    min_level: 3,
  },
  {
    code: 'healthy_lifestyle_counselling',
    label: 'Consejo general sobre estilos de vida cardiosaludables',
    domain: 'Health Education and Promotion of Healthy Lifestyles',
    cmo_pillar: 'capacidad',
    min_level: 3,
  },
  {
    code: 'self_management_tools_basic',
    label: 'Promoción de herramientas básicas de autocuidado',
    domain: 'Health Education and Promotion of Healthy Lifestyles',
    cmo_pillar: 'capacidad',
    min_level: 3,
  },
  {
    code: 'prevention_adherence_education',
    label: 'Educación sobre prevención y relevancia de la adherencia',
    domain: 'Health Education and Promotion of Healthy Lifestyles',
    cmo_pillar: 'motivacion',
    min_level: 3,
  },
  {
    code: 'bp_check',
    label: 'Control de presión arterial',
    domain: 'Screening and Detection of Cardiovascular Risk Factors (CVRF)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'lipid_profile_check',
    label: 'Control de perfil lipídico',
    domain: 'Screening and Detection of Cardiovascular Risk Factors (CVRF)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'hba1c_check',
    label: 'Control de HbA1c',
    domain: 'Screening and Detection of Cardiovascular Risk Factors (CVRF)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'glucose_monitoring',
    label: 'Monitorización de glucosa',
    domain: 'Screening and Detection of Cardiovascular Risk Factors (CVRF)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'af_screening_over65',
    label: 'Cribado de fibrilación auricular en mayores de 65 años',
    domain: 'Screening and Detection of Cardiovascular Risk Factors (CVRF)',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'smoking_stage_of_change',
    label: 'Valoración de fase de cambio para deshabituación tabáquica',
    domain: 'Smoking cessation',
    cmo_pillar: 'motivacion',
    min_level: 3,
  },
  {
    code: 'motivational_interviewing_basic',
    label: 'Entrevista motivacional básica para abandono tabáquico',
    domain: 'Smoking cessation',
    cmo_pillar: 'motivacion',
    min_level: 3,
  },
  {
    code: 'smoking_basic_materials',
    label: 'Entrega de material educativo básico sobre tabaquismo',
    domain: 'Smoking cessation',
    cmo_pillar: 'capacidad',
    min_level: 3,
  },
  {
    code: 'adherence_assessment_validated_tools',
    label: 'Evaluación de adherencia con herramientas validadas',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'oportunidad',
    min_level: 3,
  },
  {
    code: 'adherence_education_basic',
    label: 'Información básica sobre adherencia y prevención de eventos cardiovasculares',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'capacidad',
    min_level: 3,
  },

  // NIVEL 2 · INTERMEDIO
  {
    code: 'pros_prems_followup',
    label: 'Seguimiento con PROs y PREMs',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'teleassistance_between_visits',
    label: 'Teleasistencia entre visitas programadas',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'appointment_planning_followup',
    label: 'Planificación activa de futuras citas de seguimiento',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'personalized_materials_patient_caregiver',
    label: 'Materiales personalizados para paciente y cuidador',
    domain: 'Health Education and Promotion of Healthy Lifestyles',
    cmo_pillar: 'capacidad',
    min_level: 2,
  },
  {
    code: 'abpm_hbpm_service',
    label: 'Monitorización ambulatoria o domiciliaria de presión arterial (ABPM/HBPM)',
    domain: 'Screening and Detection of Cardiovascular Risk Factors (CVRF)',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'smoking_personalized_guides',
    label: 'Guías personalizadas y diarios para deshabituación tabáquica',
    domain: 'Smoking cessation',
    cmo_pillar: 'capacidad',
    min_level: 2,
  },
  {
    code: 'caregiver_involvement_smoking_plan',
    label: 'Implicación de cuidadores/familia en plan de deshabituación tabáquica',
    domain: 'Smoking cessation',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'pcp_goal_alignment',
    label: 'Comunicación bidireccional con Atención Primaria para alinear objetivos',
    domain: 'Coordination with the Primary Care Physician (PCP)',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'social_determinants_action',
    label: 'Actuación sobre determinantes sociales de la salud detectados',
    domain: 'Coordination with the Primary Care Physician (PCP)',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'adherence_barrier_interview',
    label: 'Entrevista clínica para detectar barreras específicas de adherencia',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'motivacion',
    min_level: 2,
  },
  {
    code: 'tailored_medication_chart',
    label: 'Esquema individualizado de medicación',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'capacidad',
    min_level: 2,
  },
  {
    code: 'patient_log_for_adherence',
    label: 'Registro/diario del paciente para apoyo a la adherencia',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'capacidad',
    min_level: 2,
  },
  {
    code: 'telephone_followup_adherence',
    label: 'Seguimiento telefónico programado para reforzar adherencia',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },
  {
    code: 'automated_reminders_adherence',
    label: 'Recordatorios automatizados para reforzar adherencia',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'oportunidad',
    min_level: 2,
  },

  // NIVEL 1 · PRIORITARIO
  {
    code: 'shared_pharmacotherapeutic_plan',
    label: 'Plan farmacoterapéutico compartido con el paciente',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'motivacion',
    min_level: 1,
  },
  {
    code: 'structured_risk_factor_program',
    label: 'Programa estructurado de detección, prevención y manejo de factores de riesgo',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'telemedicine_risk_factor_management',
    label: 'Uso de telemedicina para seguimiento intensivo de factores de riesgo',
    domain: 'Pharmacotherapeutic Follow-up (PTFU)',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'smoking_firm_personalized_advice',
    label: 'Consejo firme, personalizado y no enjuiciador para abandono tabáquico',
    domain: 'Smoking cessation',
    cmo_pillar: 'motivacion',
    min_level: 1,
  },
  {
    code: 'smoking_structured_cessation_plan',
    label: 'Plan estructurado de deshabituación tabáquica',
    domain: 'Smoking cessation',
    cmo_pillar: 'motivacion',
    min_level: 1,
  },
  {
    code: 'smoking_pharmacotherapy_review',
    label: 'Revisión y validación de farmacoterapia para abandono tabáquico',
    domain: 'Smoking cessation',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'smoking_real_time_telemonitoring',
    label: 'Telemonitorización en tiempo real de síntomas de abstinencia y riesgo de recaída',
    domain: 'Smoking cessation',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'fast_track_pcp_communication_smoking',
    label: 'Canal rápido con Atención Primaria para incidencias del tratamiento de deshabituación',
    domain: 'Smoking cessation',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'intensive_smoking_followup',
    label: 'Seguimiento intensivo de deshabituación tabáquica cada 2–3 meses',
    domain: 'Smoking cessation',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'fast_track_healthcare_team_adr',
    label: 'Canal rápido con el equipo sanitario para RAM/incidencias',
    domain: 'Coordination with the Primary Care Physician (PCP)',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'cross_level_care_transition_plan',
    label: 'Plan de acción inter-niveles para transiciones clínicas complejas',
    domain: 'Coordination with the Primary Care Physician (PCP)',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
  {
    code: 'mds_spd_complex_regimen',
    label: 'Sistema personalizado de dosificación (SPD/MDS) para régimen complejo',
    domain: 'Medication Adherence Improvement',
    cmo_pillar: 'oportunidad',
    min_level: 1,
  },
];
